name: "Web server andrzejow.net"
version: "1.10.2"
slug: "andrzejow_net"
description: "Serwer WWW dla andrzejow.net"
arch:
  - "aarch64"
  - "amd64"
startup: "services"
boot: "auto"
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Port HTTP serwera WWW andrzejow.net"
map:
  - "config:rw"
  - "share:rw"
options:
  api_key: ""
  channel_handle: ""
  target_users: []
  admin_trusted_ips:
    - "195.74.49.211"
    - "192.168.12.223"
    - "127.0.0.1"
  admin_password: "admin"
schema:
  api_key: "str?"
  channel_handle: "str?"
  target_users:
    - "str?"
  admin_trusted_ips:
    - "str?"
  admin_password: "str?"
